/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author juanmartinhurtado
 */
public class Agenda extends javax.swing.JFrame {
    
    DefaultTableModel modelo = new DefaultTableModel();
   
    /**
     * Creates new form Registro
     */
    public Agenda() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Registros guardados.");
        cargarModelo();
    }
    
    private void cargarModelo(){
        try{
            modelo.addColumn("Nombre");            
            modelo.addColumn("Apellidos");            
            modelo.addColumn("Carrera");            
            modelo.addColumn("Sexo");
            tablaRegistro.setModel(modelo);
            cargarArchivo();
        }catch(IOException e){
            System.out.println(e);
        }
    }
    
    private void cargarArchivo() throws IOException{
        String fila[];
        try{
            FileReader archivo = new FileReader("AgendaContactos.txt");
            BufferedReader lectura = new BufferedReader(archivo);
            String linea = lectura.readLine();
            
            while(linea != null){
                fila = linea.split("%");
                modelo.addRow(fila);
                linea = lectura.readLine();
            }
        }catch(FileNotFoundException e){
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        registroLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaRegistro = new javax.swing.JTable();
        atrasRegistroButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuItemCalculadora = new javax.swing.JMenu();
        menuItemSistemas = new javax.swing.JMenu();
        menuItemFGeo = new javax.swing.JMenu();
        menuItemTemp = new javax.swing.JMenu();
        menuItemAgenda = new javax.swing.JMenu();
        mainBotonRegistro = new javax.swing.JMenuItem();
        mainBotonAgenda = new javax.swing.JMenuItem();
        menuItemArchivo = new javax.swing.JMenu();
        mainBotonCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        registroLabel.setText("Agenda");

        tablaRegistro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaRegistro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(registroLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registroLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        atrasRegistroButton.setText("Atrás");
        atrasRegistroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasRegistroButtonActionPerformed(evt);
            }
        });

        menuItemCalculadora.setText("Calculadora");
        jMenuBar1.add(menuItemCalculadora);

        menuItemSistemas.setText("Sistemas");
        jMenuBar1.add(menuItemSistemas);

        menuItemFGeo.setText("Figuras");
        jMenuBar1.add(menuItemFGeo);

        menuItemTemp.setText("Temperatura");
        jMenuBar1.add(menuItemTemp);

        menuItemAgenda.setText("Agenda");

        mainBotonRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiapp/icon/contact.png"))); // NOI18N
        mainBotonRegistro.setText("Registro");
        mainBotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBotonRegistroActionPerformed(evt);
            }
        });
        menuItemAgenda.add(mainBotonRegistro);

        mainBotonAgenda.setText("Agenda");
        mainBotonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBotonAgendaActionPerformed(evt);
            }
        });
        menuItemAgenda.add(mainBotonAgenda);

        jMenuBar1.add(menuItemAgenda);

        menuItemArchivo.setText("Archivo");

        mainBotonCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mainBotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiapp/icon/close.png"))); // NOI18N
        mainBotonCerrar.setText("Cerrar");
        mainBotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBotonCerrarActionPerformed(evt);
            }
        });
        menuItemArchivo.add(mainBotonCerrar);

        jMenuBar1.add(menuItemArchivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(atrasRegistroButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(atrasRegistroButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atrasRegistroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasRegistroButtonActionPerformed
        MainMenu main = new MainMenu();
        this.setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_atrasRegistroButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
                if(JOptionPane.showConfirmDialog(null, "Deseas cerrar?","Mensaje",JOptionPane.YES_NO_OPTION)==0){
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void mainBotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBotonRegistroActionPerformed
        Registro registro = new Registro();
        this.setVisible(false);
        registro.setVisible(true);
    }//GEN-LAST:event_mainBotonRegistroActionPerformed

    private void mainBotonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBotonAgendaActionPerformed
        Agenda agenda = new Agenda();
        this.setVisible(false);
        agenda.setVisible(true);
    }//GEN-LAST:event_mainBotonAgendaActionPerformed

    private void mainBotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBotonCerrarActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseas cerrar?","Mensaje",JOptionPane.YES_NO_OPTION)==0){
            System.exit(0);
        }
    }//GEN-LAST:event_mainBotonCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atrasRegistroButton;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mainBotonAgenda;
    private javax.swing.JMenuItem mainBotonCerrar;
    private javax.swing.JMenuItem mainBotonRegistro;
    private javax.swing.JMenu menuItemAgenda;
    private javax.swing.JMenu menuItemArchivo;
    private javax.swing.JMenu menuItemCalculadora;
    private javax.swing.JMenu menuItemFGeo;
    private javax.swing.JMenu menuItemSistemas;
    private javax.swing.JMenu menuItemTemp;
    private javax.swing.JLabel registroLabel;
    private javax.swing.JTable tablaRegistro;
    // End of variables declaration//GEN-END:variables
}
