/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

/**
 *
 * @author juanmartinhurtado
 */
public class CalculadoraFigurasGeométricas extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraFigurasGeométricas
     */
    public CalculadoraFigurasGeométricas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selecciónFigura = new javax.swing.JPanel();
        figuraLabel = new javax.swing.JLabel();
        circuloButton = new javax.swing.JRadioButton();
        cuadradoButton = new javax.swing.JRadioButton();
        trianguloButton = new javax.swing.JRadioButton();
        poligonoButton = new javax.swing.JRadioButton();
        textFieldLado1 = new javax.swing.JTextField();
        textFieldLado2 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuItemCalculadora = new javax.swing.JMenu();
        menuItemSistemas = new javax.swing.JMenu();
        menuItemFGeo = new javax.swing.JMenu();
        menuItemTemp = new javax.swing.JMenu();
        menuItemAgenda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        figuraLabel.setText("Figura");

        circuloButton.setText("Círculo");
        circuloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circuloButtonActionPerformed(evt);
            }
        });

        cuadradoButton.setText("Cuadrado");

        trianguloButton.setText("Triángulo");
        trianguloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trianguloButtonActionPerformed(evt);
            }
        });

        poligonoButton.setText("Polígono");

        javax.swing.GroupLayout selecciónFiguraLayout = new javax.swing.GroupLayout(selecciónFigura);
        selecciónFigura.setLayout(selecciónFiguraLayout);
        selecciónFiguraLayout.setHorizontalGroup(
            selecciónFiguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecciónFiguraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(selecciónFiguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(figuraLabel)
                    .addComponent(circuloButton)
                    .addComponent(cuadradoButton)
                    .addComponent(trianguloButton)
                    .addComponent(poligonoButton))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        selecciónFiguraLayout.setVerticalGroup(
            selecciónFiguraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(selecciónFiguraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(figuraLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(circuloButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuadradoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trianguloButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poligonoButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        textFieldLado1.setText("jTextField1");

        textFieldLado2.setText("jTextField2");

        menuItemCalculadora.setText("Calculadora");
        jMenuBar1.add(menuItemCalculadora);

        menuItemSistemas.setText("Sistemas");
        jMenuBar1.add(menuItemSistemas);

        menuItemFGeo.setText("Figuras");
        jMenuBar1.add(menuItemFGeo);

        menuItemTemp.setText("Temperatura");
        jMenuBar1.add(menuItemTemp);

        menuItemAgenda.setText("Agenda");
        jMenuBar1.add(menuItemAgenda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selecciónFigura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldLado1)
                    .addComponent(textFieldLado2))
                .addContainerGap(554, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selecciónFigura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textFieldLado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textFieldLado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void circuloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circuloButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_circuloButtonActionPerformed

    private void trianguloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trianguloButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trianguloButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFigurasGeométricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFigurasGeométricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFigurasGeométricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraFigurasGeométricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraFigurasGeométricas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton circuloButton;
    private javax.swing.JRadioButton cuadradoButton;
    private javax.swing.JLabel figuraLabel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuItemAgenda;
    private javax.swing.JMenu menuItemCalculadora;
    private javax.swing.JMenu menuItemFGeo;
    private javax.swing.JMenu menuItemSistemas;
    private javax.swing.JMenu menuItemTemp;
    private javax.swing.JRadioButton poligonoButton;
    private javax.swing.JPanel selecciónFigura;
    private javax.swing.JTextField textFieldLado1;
    private javax.swing.JTextField textFieldLado2;
    private javax.swing.JRadioButton trianguloButton;
    // End of variables declaration//GEN-END:variables
}
