/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

/**
 *
 * @author juanmartinhurtado
 */
public class ConvertidorSistemas extends javax.swing.JFrame {

    /**
     * Creates new form ConvertidorSistemas
     */
    public ConvertidorSistemas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGSistemas = new javax.swing.ButtonGroup();
        seleccionSistema = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rBDecimal = new javax.swing.JRadioButton();
        rBBinario = new javax.swing.JRadioButton();
        rBOctal = new javax.swing.JRadioButton();
        rBHexadecimal = new javax.swing.JRadioButton();
        tFNumero = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Salida = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        menuBarGlobal = new javax.swing.JMenuBar();
        menuItemCalculadora = new javax.swing.JMenu();
        menuItemSistemas = new javax.swing.JMenu();
        menuItemFGeo = new javax.swing.JMenu();
        menuItemTemp = new javax.swing.JMenu();
        menuItemAgenda = new javax.swing.JMenu();
        mainBotonRegistro = new javax.swing.JMenuItem();
        mainBotonAgenda = new javax.swing.JMenuItem();
        menuItemArchivo = new javax.swing.JMenu();
        mainBotonCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Sistema origen");

        bGSistemas.add(rBDecimal);
        rBDecimal.setText("Decimal");

        bGSistemas.add(rBBinario);
        rBBinario.setText("Binario");

        bGSistemas.add(rBOctal);
        rBOctal.setText("Octal");

        bGSistemas.add(rBHexadecimal);
        rBHexadecimal.setText("Hexadecimal");
        rBHexadecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBHexadecimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout seleccionSistemaLayout = new javax.swing.GroupLayout(seleccionSistema);
        seleccionSistema.setLayout(seleccionSistemaLayout);
        seleccionSistemaLayout.setHorizontalGroup(
            seleccionSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionSistemaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seleccionSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(rBDecimal)
                    .addComponent(rBBinario)
                    .addComponent(rBOctal)
                    .addComponent(rBHexadecimal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        seleccionSistemaLayout.setVerticalGroup(
            seleccionSistemaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionSistemaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBDecimal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBBinario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rBOctal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rBHexadecimal)
                .addContainerGap())
        );

        tFNumero.setText("jTextField1");
        tFNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFNumeroActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout SalidaLayout = new javax.swing.GroupLayout(Salida);
        Salida.setLayout(SalidaLayout);
        SalidaLayout.setHorizontalGroup(
            SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        SalidaLayout.setVerticalGroup(
            SalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        menuItemCalculadora.setText("Calculadora");
        menuBarGlobal.add(menuItemCalculadora);

        menuItemSistemas.setText("Sistemas");
        menuBarGlobal.add(menuItemSistemas);

        menuItemFGeo.setText("Figuras");
        menuBarGlobal.add(menuItemFGeo);

        menuItemTemp.setText("Temperatura");
        menuBarGlobal.add(menuItemTemp);

        menuItemAgenda.setText("Agenda");

        mainBotonRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiapp/icon/contact.png"))); // NOI18N
        mainBotonRegistro.setText("Registro");
        mainBotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBotonRegistroActionPerformed(evt);
            }
        });
        menuItemAgenda.add(mainBotonRegistro);

        mainBotonAgenda.setText("Agenda");
        mainBotonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBotonAgendaActionPerformed(evt);
            }
        });
        menuItemAgenda.add(mainBotonAgenda);

        menuBarGlobal.add(menuItemAgenda);

        menuItemArchivo.setText("Archivo");

        mainBotonCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mainBotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiapp/icon/close.png"))); // NOI18N
        mainBotonCerrar.setText("Cerrar");
        mainBotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBotonCerrarActionPerformed(evt);
            }
        });
        menuItemArchivo.add(mainBotonCerrar);

        menuBarGlobal.add(menuItemArchivo);

        setJMenuBar(menuBarGlobal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seleccionSistema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tFNumero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 443, Short.MAX_VALUE)
                        .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seleccionSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tFNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainBotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBotonRegistroActionPerformed
        Registro registro = new Registro();
        this.setVisible(false);
        registro.setVisible(true);
    }//GEN-LAST:event_mainBotonRegistroActionPerformed

    private void mainBotonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBotonAgendaActionPerformed
        Agenda agenda = new Agenda();
        this.setVisible(false);
        agenda.setVisible(true);
    }//GEN-LAST:event_mainBotonAgendaActionPerformed

    private void mainBotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBotonCerrarActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseas cerrar?","Mensaje",JOptionPane.YES_NO_OPTION)==0){
            System.exit(0);
        }
    }//GEN-LAST:event_mainBotonCerrarActionPerformed

    private void tFNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFNumeroActionPerformed

    private void rBHexadecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBHexadecimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBHexadecimalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConvertidorSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConvertidorSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConvertidorSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConvertidorSistemas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConvertidorSistemas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Salida;
    private javax.swing.ButtonGroup bGSistemas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem mainBotonAgenda;
    private javax.swing.JMenuItem mainBotonCerrar;
    private javax.swing.JMenuItem mainBotonRegistro;
    private javax.swing.JMenuBar menuBarGlobal;
    private javax.swing.JMenu menuItemAgenda;
    private javax.swing.JMenu menuItemArchivo;
    private javax.swing.JMenu menuItemCalculadora;
    private javax.swing.JMenu menuItemFGeo;
    private javax.swing.JMenu menuItemSistemas;
    private javax.swing.JMenu menuItemTemp;
    private javax.swing.JRadioButton rBBinario;
    private javax.swing.JRadioButton rBDecimal;
    private javax.swing.JRadioButton rBHexadecimal;
    private javax.swing.JRadioButton rBOctal;
    private javax.swing.JPanel seleccionSistema;
    private javax.swing.JTextField tFNumero;
    // End of variables declaration//GEN-END:variables
}
