/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import javax.swing.JOptionPane;

/**
 *
 * @author juanmartinhurtado
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        menuBarGlobal = new javax.swing.JMenuBar();
        menuItemCalculadora = new javax.swing.JMenu();
        menuItemSistemas = new javax.swing.JMenu();
        menuItemFGeo = new javax.swing.JMenu();
        menuItemTemp = new javax.swing.JMenu();
        menuItemAgenda = new javax.swing.JMenu();
        mainBotonRegistro = new javax.swing.JMenuItem();
        mainBotonAgenda = new javax.swing.JMenuItem();
        menuItemArchivo = new javax.swing.JMenu();
        mainBotonCerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuItemCalculadora.setText("Calculadora");
        menuBarGlobal.add(menuItemCalculadora);

        menuItemSistemas.setText("Sistemas");
        menuBarGlobal.add(menuItemSistemas);

        menuItemFGeo.setText("Figuras");
        menuBarGlobal.add(menuItemFGeo);

        menuItemTemp.setText("Temperatura");
        menuBarGlobal.add(menuItemTemp);

        menuItemAgenda.setText("Agenda");

        mainBotonRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiapp/icon/contact.png"))); // NOI18N
        mainBotonRegistro.setText("Registro");
        mainBotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBotonRegistroActionPerformed(evt);
            }
        });
        menuItemAgenda.add(mainBotonRegistro);

        mainBotonAgenda.setText("Agenda");
        mainBotonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBotonAgendaActionPerformed(evt);
            }
        });
        menuItemAgenda.add(mainBotonAgenda);

        menuBarGlobal.add(menuItemAgenda);

        menuItemArchivo.setText("Archivo");

        mainBotonCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mainBotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiapp/icon/close.png"))); // NOI18N
        mainBotonCerrar.setText("Cerrar");
        mainBotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBotonCerrarActionPerformed(evt);
            }
        });
        menuItemArchivo.add(mainBotonCerrar);

        menuBarGlobal.add(menuItemArchivo);

        setJMenuBar(menuBarGlobal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainBotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBotonRegistroActionPerformed
        Registro registro = new Registro();
        this.setVisible(false);
        registro.setVisible(true);
    }//GEN-LAST:event_mainBotonRegistroActionPerformed

    private void mainBotonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBotonAgendaActionPerformed
        Agenda agenda = new Agenda();
        this.setVisible(false);
        agenda.setVisible(true);
    }//GEN-LAST:event_mainBotonAgendaActionPerformed

    private void mainBotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBotonCerrarActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseas cerrar?","Mensaje",JOptionPane.YES_NO_OPTION)==0){
            System.exit(0);
        }
    }//GEN-LAST:event_mainBotonCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem mainBotonAgenda;
    private javax.swing.JMenuItem mainBotonCerrar;
    private javax.swing.JMenuItem mainBotonRegistro;
    private javax.swing.JMenuBar menuBarGlobal;
    private javax.swing.JMenu menuItemAgenda;
    private javax.swing.JMenu menuItemArchivo;
    private javax.swing.JMenu menuItemCalculadora;
    private javax.swing.JMenu menuItemFGeo;
    private javax.swing.JMenu menuItemSistemas;
    private javax.swing.JMenu menuItemTemp;
    // End of variables declaration//GEN-END:variables
}
