/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal;

import javax.swing.JOptionPane;

/**
 *
 * @author juanmartinhurtado
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        BGSexo = new javax.swing.ButtonGroup();
        Name = new javax.swing.JLabel();
        Apellidos = new javax.swing.JLabel();
        Carrera = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        apellidosTextField = new javax.swing.JTextField();
        carreraTextField = new javax.swing.JTextField();
        Sexo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MasculinoButton = new javax.swing.JRadioButton();
        FemeninoButton = new javax.swing.JRadioButton();
        Enviar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuItemCalculadora = new javax.swing.JMenu();
        menuItemSistemas = new javax.swing.JMenu();
        menuItemFGeo = new javax.swing.JMenu();
        menuItemTemp = new javax.swing.JMenu();
        menuItemAgenda = new javax.swing.JMenu();
        mainBotonRegistro = new javax.swing.JMenuItem();
        mainBotonAgenda = new javax.swing.JMenuItem();
        menuItemArchivo = new javax.swing.JMenu();
        mainBotonCerrar = new javax.swing.JMenuItem();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Name.setDisplayedMnemonic('N');
        Name.setLabelFor(nameTextField);
        Name.setText("Name");

        Apellidos.setDisplayedMnemonic('P');
        Apellidos.setLabelFor(apellidosTextField);
        Apellidos.setText("Apellidos");

        Carrera.setDisplayedMnemonic('C');
        Carrera.setLabelFor(carreraTextField);
        Carrera.setText("Carrera");

        apellidosTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosTextFieldActionPerformed(evt);
            }
        });

        carreraTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carreraTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Sexo");

        BGSexo.add(MasculinoButton);
        MasculinoButton.setText("Masculino");
        MasculinoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasculinoButtonActionPerformed(evt);
            }
        });

        BGSexo.add(FemeninoButton);
        FemeninoButton.setText("Femenino");
        FemeninoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemeninoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SexoLayout = new javax.swing.GroupLayout(Sexo);
        Sexo.setLayout(SexoLayout);
        SexoLayout.setHorizontalGroup(
            SexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SexoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(MasculinoButton)
                    .addComponent(FemeninoButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        SexoLayout.setVerticalGroup(
            SexoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SexoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MasculinoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FemeninoButton)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Enviar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiapp/icon/send(1).png"))); // NOI18N
        Enviar.setText("Enviar");
        Enviar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/guiapp/icon/send.png"))); // NOI18N
        Enviar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/guiapp/icon/send(2).png"))); // NOI18N
        Enviar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/guiapp/icon/send(2).png"))); // NOI18N
        Enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarActionPerformed(evt);
            }
        });

        menuItemCalculadora.setText("Calculadora");
        jMenuBar1.add(menuItemCalculadora);

        menuItemSistemas.setText("Sistemas");
        jMenuBar1.add(menuItemSistemas);

        menuItemFGeo.setText("Figuras");
        jMenuBar1.add(menuItemFGeo);

        menuItemTemp.setText("Temperatura");
        jMenuBar1.add(menuItemTemp);

        menuItemAgenda.setText("Agenda");

        mainBotonRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiapp/icon/contact.png"))); // NOI18N
        mainBotonRegistro.setText("Registro");
        mainBotonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBotonRegistroActionPerformed(evt);
            }
        });
        menuItemAgenda.add(mainBotonRegistro);

        mainBotonAgenda.setText("Agenda");
        mainBotonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBotonAgendaActionPerformed(evt);
            }
        });
        menuItemAgenda.add(mainBotonAgenda);

        jMenuBar1.add(menuItemAgenda);

        menuItemArchivo.setText("Archivo");

        mainBotonCerrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mainBotonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guiapp/icon/close.png"))); // NOI18N
        mainBotonCerrar.setText("Cerrar");
        mainBotonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBotonCerrarActionPerformed(evt);
            }
        });
        menuItemArchivo.add(mainBotonCerrar);

        jMenuBar1.add(menuItemArchivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Name))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Apellidos)
                            .addComponent(Carrera)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellidosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(carreraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Enviar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Name)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Apellidos)
                        .addGap(6, 6, 6)
                        .addComponent(apellidosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Carrera))
                    .addComponent(Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(carreraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(Enviar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apellidosTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosTextFieldActionPerformed

    private void carreraTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carreraTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carreraTextFieldActionPerformed

    private void MasculinoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasculinoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasculinoButtonActionPerformed

    private void FemeninoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemeninoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemeninoButtonActionPerformed

    private void EnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarActionPerformed
        Archivo archivo = new Archivo();
        archivo.crearArchivo();
        
        if (nameTextField.getText().equals("") || apellidosTextField.getText().equals("") || carreraTextField.getText().equals("") || ((MasculinoButton.isSelected()== false) && (FemeninoButton.isSelected()==false))) {
            JOptionPane.showMessageDialog(null, "Por favor, llene los campos.");
        }else{
        
        String nombre = nameTextField.getText ();
        String apellidos = apellidosTextField.getText ();
        String carrera = carreraTextField.getText();
        String sexo = sexoSeleccion();
        
        Persona persona = new Persona (nombre, apellidos, carrera,sexo);
        archivo.escribirEnArchivo(persona);
        
        JOptionPane.showMessageDialog(null, "Registro guardado.");
        
        Reset();
        
        }
    }//GEN-LAST:event_EnviarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        
        if(JOptionPane.showConfirmDialog(null, "Deseas cerrar?","Mensaje",JOptionPane.YES_NO_OPTION)==0){
            System.exit(0);
        }
        
    }//GEN-LAST:event_formWindowClosing

    private void mainBotonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBotonRegistroActionPerformed
        Registro registro = new Registro();
        this.setVisible(false);
        registro.setVisible(true);
    }//GEN-LAST:event_mainBotonRegistroActionPerformed

    private void mainBotonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBotonAgendaActionPerformed
        Agenda agenda = new Agenda();
        this.setVisible(false);
        agenda.setVisible(true);
    }//GEN-LAST:event_mainBotonAgendaActionPerformed

    private void mainBotonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBotonCerrarActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseas cerrar?","Mensaje",JOptionPane.YES_NO_OPTION)==0){
            System.exit(0);
        }
    }//GEN-LAST:event_mainBotonCerrarActionPerformed

    private String sexoSeleccion(){
        String sexo = "";
        if(MasculinoButton.isSelected() == true){
            sexo = "Masculino";
        }else if(FemeninoButton.isSelected() == true){
            sexo = "Femenino";
        }
        return sexo;
    }
    
    private void Reset(){
        nameTextField.setText("");
        apellidosTextField.setText("");
        carreraTextField.setText("");
        MasculinoButton.setSelected(false);
        FemeninoButton.setSelected(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }
    
    private void closew(){
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Apellidos;
    private javax.swing.ButtonGroup BGSexo;
    private javax.swing.JLabel Carrera;
    private javax.swing.JButton Enviar;
    private javax.swing.JRadioButton FemeninoButton;
    private javax.swing.JRadioButton MasculinoButton;
    private javax.swing.JLabel Name;
    private javax.swing.JPanel Sexo;
    private javax.swing.JTextField apellidosTextField;
    private javax.swing.JTextField carreraTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mainBotonAgenda;
    private javax.swing.JMenuItem mainBotonCerrar;
    private javax.swing.JMenuItem mainBotonRegistro;
    private javax.swing.JMenu menuItemAgenda;
    private javax.swing.JMenu menuItemArchivo;
    private javax.swing.JMenu menuItemCalculadora;
    private javax.swing.JMenu menuItemFGeo;
    private javax.swing.JMenu menuItemSistemas;
    private javax.swing.JMenu menuItemTemp;
    private javax.swing.JTextField nameTextField;
    // End of variables declaration//GEN-END:variables
}
